export const db = [
  {
    nombre: "chamarra azul Levi's",
    marca: "Levi's",
    tipo: "chamarra",
    precio: 199.99,
    color: "azul",
    tela: "mezclilla",
    genero: "h",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/1.jpg?alt=media&token=fefe982c-320f-475d-b9f9-ea6de5b1ad25",
  },
  {
    nombre: "chamarra azul Levi's",

    marca: "Levi's",
    tipo: "chamarra",
    precio: 159.99,
    color: "azul",
    tela: "mezclilla",
    genero: "h",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/2.jpg?alt=media&token=6fbb9317-b6b1-40ef-a1ce-7ed023afcddb",
  },
  {
    nombre: "jeans azul Guess",

    marca: "Guess",
    tipo: "jeans",
    precio: 234.99,
    color: "azul",
    tela: "mezclilla",
    genero: "m",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/3.jpg?alt=media&token=7717fc03-1bd2-4065-96fc-eb6e807cbcfb",
  },
  {
    nombre: "jeans azul Guess",

    marca: "Guess",
    tipo: "jeans",
    precio: 234.99,
    color: "azul",
    tela: "mezclilla",
    genero: "m",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/4.jpg?alt=media&token=9962e9a3-51cd-4833-b88e-c380bcb314e9",
  },
  {
    nombre: "jeans azul Guess",
    marca: "Guess",
    tipo: "jeans",
    precio: 234.99,
    color: "azul",
    tela: "mezclilla",
    genero: "m",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/5.jpg?alt=media&token=d621f994-16a5-486a-9066-cc659206636c",
  },
  {
    nombre: "vestido marron Guess",
    marca: "Guess",
    tipo: "vestido",
    precio: 399.99,
    color: "marron",
    tela: "poliéster",
    genero: "m",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/6.jpg?alt=media&token=dad058bd-0a67-4b33-a4f4-092f2bc90c87",
  },
  {
    nombre: "vestido marron Guess",
    marca: "Guess",
    tipo: "vestido",
    precio: 249.99,
    color: "marron",
    tela: "poliéster",
    genero: "m",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/7.jpg?alt=media&token=cc069f0b-e317-48fe-bb0f-c5b190dbd045",
  },
  {
    nombre: "vestido marron Guess",
    marca: "Guess",
    tipo: "vestido",
    precio: 159.99,
    color: "marron",
    tela: "satin",
    genero: "m",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/8.jpg?alt=media&token=a73278f5-dbb5-41f5-be94-903ff793fe80",
  },
  {
    nombre: "blusa amarillo Guess",
    marca: "Guess",
    tipo: "blusa",
    precio: 99.99,
    color: "amarillo",
    tela: "satín",
    genero: "m",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/9.jpg?alt=media&token=7580ebe6-4201-4ac0-889f-37170344d7d1",
  },
  {
    nombre: "blusa amarilla Guess",
    marca: "Guess",
    tipo: "blusa",
    precio: 109.99,
    color: "amarillo",
    tela: "algodon",
    genero: "m",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/10.jpg?alt=media&token=840562e2-2da2-42e9-a2e8-6c1d477deee8",
  },
  {
    nombre: "bolsa negro Guess",
    marca: "Guess",
    tipo: "bolsa",
    precio: 349.99,
    color: "negro",
    tela: "piel sintetica",
    genero: "m",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/13.jpg?alt=media&token=bf797a64-550a-49af-a95e-f145cbd43c1b",
  },
  {
    nombre: "bolsa negro Guess",
    marca: "Guess",
    tipo: "bolsa",
    precio: 349.99,
    color: "negro",
    tela: "piel sintetica",
    genero: "m",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/14.jpg?alt=media&token=9ff0b402-488a-48ef-ba40-4cdb3d960169",
  },
  {
    nombre: "bolsa rosa Guess",
    marca: "Guess",
    tipo: "bolsa",
    precio: 499.99,
    color: "rosa",
    tela: "piel sintetica",
    genero: "m",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/16.jpg?alt=media&token=3b12beb3-a5fe-43c6-b120-752c9f5ec4a9",
  },
  {
    nombre: "bolsa amarillo Guess",
    marca: "Guess",
    tipo: "bolsa",
    precio: 289.99,
    color: "amarillo",
    tela: "piel sintetica",
    genero: "m",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerse-eaf57.appspot.com/o/17.jpg?alt=media&token=847214da-875f-4608-959f-519fc0a79d61",
  },
];